# Copyright (c) Microsoft Corp. All Rights Reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

[package]
name = "azure_messaging_eventhubs_checkpointstore_blob"
version = "0.5.0"
description = "Azure Event Hubs checkpoint store implementation using Azure Blob Storage"
readme = "README.md"
license = "MIT"
repository = "https://github.com/azure/azure-sdk-for-rust"
homepage = "https://github.com/azure/azure-sdk-for-rust"
authors = ["Microsoft"]
keywords = ["sdk", "azure", "messaging", "cloud", "eventhubs"]
categories = ["api-bindings"]
documentation = "https://docs.rs/azure_messaging_eventhubs_checkpointstore_blob"
edition = "2024"

[dependencies]
async-trait = "0.1"
azure_core = "0.32.0"
azure_messaging_eventhubs = { path = "../azure_messaging_eventhubs", version = "0.11.0" }
azure_storage_blob = "0.9.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.41", features = ["serde"] }
tracing = "0.1.40"
uuid = { version = "1.18", features = ["v4", "serde"] }

[features]
default = ["azure_core/default"]
